### ISSUE TITLE
Need user-friendly way to transfer files in and out of WSA

### ISSUE THREAD

**Issue by arlomedia** [microsoft/WSA#111]
### Is your feature request related to a problem? Please describe

Will WSA eventually have a user-friendly way to share files between WSA and Windows? I see that developers can use adb to push and pull files, and some online forums describe sideloading Android file manager apps and setting up network connections to the main Windows system, but I wouldn't consider either of these to be suitable for end users.

Of the two Android apps I'm testing for Windows 11 release, one relies on loading and saving local files to an extent that it probably won't be worth releasing if this is not available.

### Describe the solution you'd like

My apps use the `ACTION_GET_CONTENT` and `ACTION_CREATE_DOCUMENT` intents to open Android file pickers to load and save files. Currently this file picker only shows the WSA filesystem, labeled as "Subsystem for Android." The ideal solution would be to show "Windows" as another source that users can browse in the file picker. Then users could open a file saved in their Windows directories or save a file to their Windows directories.

Another solution would be showing cloud storage services like Dropbox in the file pickers. Then users could copy files from Windows to Dropbox and then access them from Dropbox in WSA. Maybe this already works, but I haven't been able to test it because Dropbox, Google Drive, etc. aren't yet available in the Amazon App Store on Windows devices.

Another solution would be enabling drag-and-drop of files between the WSA "Files" window and a Windows File Explorer window. I tried this but when dragging a Windows file to the WSA Files window, it showed a "not allowed" icon. Going the other direction, files in the WSA Files window could not be dragged at all.

### Describe alternatives you've considered

adb - too technical for end users
sideloading file manager apps - too technical for end users
cloud service as a go-between - not currently available, don't know if it will be available
drag and drop between file explorer windows - not available

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by arlomedia** [comment]
Great, this will make my app suitable for a Windows release.

**Comment by Chris2011** [comment]
I dunno whether this is related to this but I'm searching for a similar feature like the android studio has, called device file explorer. I know, that WSA can show me the normal user folders like Android, Downloads, DCIM, etc. but all the system folders are missing, like lost+found and so on. My app is writing a database to the file and this folder is not visible for a normal user of my app.

**Comment by ArthurKun021** [comment]
if possible, if it can be like the WSL where you can transfer files via the file explorer

**Comment by master255** [comment]
@nieubank I think without support for this functionality - your subsystem is in alpha version.

**Comment by jake-brown-maps** [comment]
A common user story we would like to have supported with the file transfer feature:  A WSA user downloads a certificate from Windows Edge Browser and imports that cert into WSA trust store.

**Comment by massimobio** [comment]
Any updates on this? Our app is crippled by the inability to open files #114, so I'm hoping to see this implemented soon 🤞

**Comment by massimobio** [comment]
Any updates on this? Our app is crippled by the inability to open files #114, so I'm hoping to see this implemented soon 🤞

**Comment by zadesai** [comment]
Hi, we are investigating solutions for the feature, but don't have details to share at this time.

**Comment by pc-v2** [comment]
I want to access D:\ or other directory, if possible

**Comment by raaomoka** [comment]
> Hi, this is something on our radar already for new feature requests, we appreciate the feedback here!

Hey zadesai, while you folks are looking into this, could you also consider enabling file sharing via the Windows and Android Share Panels instead of just their file systems? That's a totally different and more direct means of sharing data with Android apps, and it enables loads of productivity benefits from Android on our phones, which we currently can only dream of on Windows.

As described in this Feedback ( https://aka.ms/AAl24ll ), one of the major benefits of Android apps on our phones is for them to receive content via the share dialog, **from ANY APP** (not just the file system app), and perform a wide variety of actions with them. Few of endless examples include:

1. Locating an address on a maps app
2. Locating a product in an online retailer app
3. Rendering a website-extracting its text-and reading it aloud all from a URL shared to the app
4. Dowloading content from a URL shared to the app
5. Tracking a parcel via a tracking number shared to the app
6. Uploading/Posting content to a site or communication platform app (literally every social media app takes advantage of this)
7. Sharing those content to other devices via NAS apps

All of this is possible with Android apps on our phones. However, with Windows Subsystem for Android, there's currently no way to directly share content to those Android apps directly via the Windows Share Dialog (especially when initiated from Edge), drastically hampering the productive uses of Android apps on Windows. Please kindly consider implementing this content sharing aspect too.

**Comment by kevinkieselbach** [comment]
We already support sharing files from Android apps to Windows apps using Android's share pane.  If you select the "Windows default preference" option, it will open the file on Windows using the file type association (copying the file to Windows Downloads if the source isn't in a shared folder).

Unfortunately, integrating Android apps into the Windows share pane isn't currently an option because only MSIX packages can register as Windows share targets.  Until Windows provides a way to programmatically register share targets, WSA can't support this, and Windows just hasn't prioritized the share experience.  As a work-around, WSA supports drag-and-drop to Android app windows and will invoke the Android app's share intent on drop.

**Comment by raaomoka** [comment]
> Unfortunately, integrating Android apps into the Windows share pane isn't currently an option because only MSIX packages can register as Windows share targets. Until Windows provides a way to programmatically register share targets, WSA can't support this, and Windows just hasn't prioritized the share experience.

That indeed is unfortunate, as it renders a major productivity enhancing aspect Android apps totally mute. No way of sending this request to Panos to actually prioritise the Windows Share Experience? Without it, the WSA experience just won't ever be complete, living a lot to be desired.

> As a work-around, WSA supports drag-and-drop to Android app windows and will invoke the Android app's share intent on drop.

Unfortunately, this work-around presumes you have the app open in the foreground, which isn't always the case, especially for Android apps that offer the following:

>3. Rendering a website-extracting its text-and reading it aloud all from a URL shared to the app
>4. Dowloading content from a URL shared to the app
>7. Sharing those content to other devices via NAS apps

**Comment by arlomedia** [comment]
> As a work-around, WSA supports drag-and-drop to Android app windows and will invoke the Android app's share intent on drop.

Would this only work for importing/opening files? Is there a way to export/save files from an app to the Windows environment?

**Comment by kevinkieselbach** [comment]
> > As a work-around, WSA supports drag-and-drop to Android app windows and will invoke the Android app's share intent on drop.
> 
> Would this only work for importing/opening files? Is there a way to export/save files from an app to the Windows environment?

Android apps should invoke an ACTION_VIEW or ACTION_SEND intent to open/share a file.  If the user selects "Windows default preference" in the chooser dialog, the file will open on Windows (copying it to downloads if necessary).  Android apps can also use ACTION_CREATE_DOCUMENT to allow the user to select a save location, which can be in the "Windows" folder.  If the Android app isn't following best practices for files, users can manually invoke ACTION_VIEW on a file from the "Files" link in WSA Settings as long as the file is in a public folder (app private folders are only accessible to that app).

**Comment by arlomedia** [comment]
My apps use ACTION_GET_CONTENT to import and ACTION_CREATE_DOCUMENT to export. I haven't seen an option to select Windows folders from the file browser. I'll try it again.

**Comment by arlomedia** [comment]
My main use case is exporting and importing .sqlite files for the purpose of backing up or moving data between devices. Here's what I see when using ACTION_CREATE_DOCUMENT to export a file from an Android app using the current Windows Subsystem For Android version 2306.40000.4.0:

1. The file browser opens, showing only "Subsystem for Android(TM)." Compared to previous WSA versions, I now see the "Windows" folder mentioned above. However, that apparently is not a link to the Windows environment, it's just a new folder within the Subsystem for Android environment.
2. I can open the Windows Subsystem For Android Settings app and click the arrow icon next to Files to browse the Subsystem For Android folders and see the file I exported, whether into a regular folder like Documents or this new Windows folder.
3. If I click the file, it opens a prompt asking me what Windows app to open it with. None of the displayed options are useful for an .sqlite file. I don't see an option to simply save the file to a location in my Windows environment. If I select the file and click the Share button, I see the "Windows default preference" option. If I click that, the same thing happens. In the previous WSA version I had, either action would copy the file to the Download folder in the Windows environment so I could then move it to my desired location. In the current version, I don't see any way to save the file to the Windows environment.

When using ACTION_GET_CONTENT to import a file, the file browser again only shows "Subsystem for Android(TM)." I don't see a way to move a file from the Windows environment into that. Dragging and dropping a file from a Windows folder to my app window or to the Windows Subsystem For Android Settings app's Files window shows a "not allowed" icon. So this seems to not be possible without developer tools like adb.

It sounds like I would have to rework my apps to use ACTION_SEND and ACTION_VIEW to access a more direct workflow. I stopped using those several years ago because they show a lot of irrelevant or confusing options on Android devices. So if I did this, I would implement separate code for Windows, and leave the functions the way they are for native Android.

It also sounds like a reworked export workflow would only present the "Windows default preference" option, which would only attempt to open the file in a Windows app. So that still wouldn't provide the functionality I'm trying to replicate. I don't see any indication of how the reworked import workflow would work.

**Comment by kevinkieselbach** [comment]
> My main use case is exporting and importing .sqlite files for the purpose of backing up or moving data between devices. Here's what I see when using ACTION_CREATE_DOCUMENT to export a file from an Android app using the current Windows Subsystem For Android version 2306.40000.4.0:
> 
> 1. The file browser opens, showing only "Subsystem for Android(TM)." Compared to previous WSA versions, I now see the "Windows" folder mentioned above. However, that apparently is not a link to the Windows environment, it's just a new folder within the Subsystem for Android environment.
> 2. I can open the Windows Subsystem For Android Settings app and click the arrow icon next to Files to browse the Subsystem For Android folders and see the file I exported, whether into a regular folder like Documents or this new Windows folder.
> 3. If I click the file, it opens a prompt asking me what Windows app to open it with. None of the displayed options are useful for an .sqlite file. I don't see an option to simply save the file to a location in my Windows environment. If I select the file and click the Share button, I see the "Windows default preference" option. If I click that, the same thing happens. In the previous WSA version I had, either action would copy the file to the Download folder in the Windows environment so I could then move it to my desired location. In the current version, I don't see any way to save the file to the Windows environment.
> 
> When using ACTION_GET_CONTENT to import a file, the file browser again only shows "Subsystem for Android(TM)." I don't see a way to move a file from the Windows environment into that. Dragging and dropping a file from a Windows folder to my app window or to the Windows Subsystem For Android Settings app's Files window shows a "not allowed" icon. So this seems to not be possible without developer tools like adb.
> 
> It sounds like I would have to rework my apps to use ACTION_SEND and ACTION_VIEW to access a more direct workflow. I stopped using those several years ago because they show a lot of irrelevant or confusing options on Android devices. So if I did this, I would implement separate code for Windows, and leave the functions the way they are for native Android.
> 
> It also sounds like a reworked export workflow would only present the "Windows default preference" option, which would only attempt to open the file in a Windows app. So that still wouldn't provide the functionality I'm trying to replicate. I don't see any indication of how the reworked import workflow would work.

The "Windows" folder in WSA is the same as the user profile folder on Windows (e.g., "C:\Users\YourUserName").  For example, it contains the user's Windows Documents and Pictures folders.  ACTION_CREATE_DOCUMENT should let the user select any folder within their Windows user profile folder, and you should be able to find the files you save in Windows File Explorer if you navigate to the corresponding folder in the user profile.

If WSA isn't copying a file to Windows Downloads when you select the "Windows default preference" option, that's because the file is already in a shared folder, so WSA instead asks Windows to open it directly from the shared folder.  If you browse your user profile folder in Windows File Explorer, you should find that file and can move it elsewhere (although it should already be where you want it since you must have selected a location in the "Windows" folder in WSA corresponding to a location in your Windows user profile folder).

ACTION_GET_CONTENT should include the "Windows" folder in WSA, so you should be able to find files in your Windows user profile.  If drag and drop isn't working for your app window, then your app probably doesn't declare an intent-filter for ACTION_SEND for that file type (WSA's drag and drop invokes ACTION_SEND since that is the most commonly supported way to transfer a file to an Android app).

Note that if you are looking for Windows files outside the user profile folder, those aren't shared with Android (unless the user manually chooses a different folder to share in WSA's settings app instead of their user profile folder).

**Comment by arlomedia** [comment]
Yes, I did have "share user folders" turned on, but that's good to know about if it's not on for regular users. But now I see the problem, and it's just a misunderstanding about how my new Windows PC is set up (I have very little experience using Windows). When I look at the file manager, it's showing me standard folders like Documents, Desktop, etc. but it turns out those are on OneDrive, not my local hard drive. So my Android app was saving to C:\Users\arlo\Documents but I was looking in C:\Users\arlo\OneDrive\Documents and not seeing any files saved there. I unpinned all the OneDrive folders from the file manager and pinned my local Documents folder instead and now I can easily copy files between my local drive and my Android app.

I first tried this with WSA version 2306.40000.4.0 and again with 2311.40000.3.0 and it worked with both.

I'm still exporting files with ACTION_CREATE_DOCUMENT and importing with ACTION_GET_CONTENT -- I haven't changed the app code at all for this -- and the file pickers open directly in both cases (no Share panel or other unwanted options). This is ideal for me. I think I can release my app now! Some other app features still aren't supported, but this was the only essential one.

I also found more info about this functionality here: https://github.com/microsoft/WSA/discussions/321
