### ISSUE TITLE
Media playback is paused when the app is minimized

### ISSUE THREAD

**Issue by lulMeow** [microsoft/WSA#118]
### Steps to reproduce

Play a media file in VLC media player or play a YouTube video in a browser (such as Firefox, Firefox Focus, Duckduckgo browser, Brave browser etc.)

### ✔️ Expected Behavior

After minimizing the app, the playback should continue just like any other Windows program

### ❌ Actual Behavior

The playback stops/pauses

### Please specify the version of Windows Subsystem for Android

2209.40000.26.0

**Comment by jaholme** [comment]
This behavior is up to the app developer to handle handle appropriately. We follow the standard application lifecycle for Android apps described here: [https://developer.android.com/guide/components/activities/activity-lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle)
If on an Android device navigating away from the application would cause the audio playback to pause, you will see similar behavior on WSA. We must follow this contract otherwise unexpected behavior could occur such as a game not automatically pausing when the user minimizes or removes focus from the application.

The media application would need to implement MediaPlayer [https://developer.android.com/guide/topics/media/mediaplayer#mpandservice](https://developer.android.com/guide/topics/media/mediaplayer#mpandservices) or another contract that allows them to continue playing back audio when they are no longer visible. 

If you have an example where the application is opting into these contracts for background playback and that is not working we would like to investigate it as a bug.
