### ISSUE TITLE
Use TRICHROME_64_32 Webview

### ISSUE THREAD

**Issue by arm64-v9a** [microsoft/WSA#174]
### Is your feature request related to a problem? Please describe

WSA currently uses 32_64 Legacy Webview, because use32bitAbi=true, the webview process is 32-bit

### Describe the solution you'd like

https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/android_native_libraries.md
https://source.chromium.org/chromium/chromium/src/+/main:build/util/android_chrome_version.py
This will improve performance, also provide a browser for WSA, and greatly reduce the size

### Please specify the version of Windows Subsystem for Android

2211.40000.7.0

**Comment by kevinkieselbach** [comment]
The standalone system webview isn't a "legacy" configuration.  It's the default configuration in all versions of AOSP including Android 13.  The primary benefit of using Trichrome is to share code between the browser and webview to reduce disk footprint if the device also includes a Chromium browser (see https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/aosp-system-integration.md#Choosing-a-WebView-variant).  WSA intentionally omits a full browser and instead provides a stub browser that redirects to the Windows default browser since a desktop browser provides better performance and user experience than a mobile browser, so we don't benefit from Trichrome (it would actually increase our disk space by including unnecessary browser components).

All webview variants on 64-bit devices, such as WSA, must include both 32-bit and 64-bit code to support both 32-bit and 64-bit applications (see https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/aosp-system-integration.md#choosing-build-options):

> The target_cpu option must be set to [the CPU architecture which corresponds to your Android build](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/android_build_instructions.md#Figuring-out-target_cpu). 64-bit builds of WebView (for arm64 or x64) include the code for both the 64-bit and corresponding 32-bit architecture, to support both 64-bit and 32-bit applications. Any Android device which is able to run 64-bit applications must use a 64-bit build: a WebView built for arm will not function correctly on an arm64 device.

It would only be possible to remove the 32-bit webview if we dropped support for 32-bit apps, which is not in our roadmap.
