### ISSUE TITLE
I want to open URLs in Windows' default browser.

### ISSUE THREAD

**Issue by HotchaiLLC** [microsoft/WSA#184]
### Is your feature request related to a problem? Please describe

When I try to open any URL from WSA,
`Intent i = new Intent(Intent.ACTION_VIEW);
i.setData(Uri.parse("https://www..."));
getContext().startActivity(i);`

Sometimes open in Windows' default browser, and
Sometimes open in WSA's inner WebView.

It seemingly depends on URL parameters.
(e.g., If URL parameters include ":", it opens in inner WebView.)

### Describe the solution you'd like

Always open URLs in Windows' default browser.
I want to specify it programmatically.

### Describe alternatives you've considered

Disable WSA's inner WebView.

### Please specify the version of Windows Subsystem for Android

2209.40000.28.0

**Comment by dabhattimsft** [comment]
Hi, thank you for this feature request. Currently this isn't on our immediate roadmap, but we're always listening to the community!

**Comment by kevinkieselbach** [comment]
WSA's WebView exists to handle OAuth logon scenarios.  We originally tried letting those go to the Windows default browser along with other URIs, but unfortunately, redirecting back to the Android app on completion was unreliable.  Many OAuth libraries expect an Android browser activity to remain open until they receive the redirect, some websites redirect to different URIs on Windows vs. Android (determined by the user agent string), and some OAuth providers like FBConnect use the same redirect URI scheme for all Android apps rather than a per-app scheme (resulting in unexpected "Open With" dialogs on Windows since Windows protocol registrations are based solely on the scheme, not the hostname).  We detect likely OAuth URIs and open them in a stub browser in Android to avoid these issues.  Any URI containing a redirect URI query parameter (i.e., a query parameter value containing a colon since that's the minimal indicator of an absolute URI) is likely to be an OAuth URI regardless of the parameter name.  Our current logic was arrived at from extensive app compat testing.

WSA's WebView activity includes a three-dots overflow menu with an "Open in default browser" option, which will redirect to the Windows default browser.  This allows users to easily switch to the Windows default browser if our heuristics made the wrong choice for a particular website.

**Comment by HotchaiLLC** [comment]
It's totally fine that I can't redirect back from the Windows browser to the Android app.

But I'd just like to specify whether to open a URL in the Windows default browser or WSA's WebView.

Because I pass a URI query parameter other than for OAuth.

e.g.
https://twitter.com/intent/tweet?text=%0A&url=https://github.com/microsoft/WSA/issues/184

I know the three-dots overflow menu is available.

But I think it'd be more convenient and friendly for users to be able to open it directly in Microsoft Edge or something since we're using "Windows".

**Comment by kevinkieselbach** [comment]
@HotchaiLLC, WSA recently added support for Android apps to launch URIs with any scheme on Windows: https://learn.microsoft.com/en-us/windows/android/wsa/#redirect-to-windows-apps. While this was introduced to support custom schemes, it works for http/https too and bypasses the heuristics that open some http/https URIs in a WebView. If you want to ensure a URI opens in Windows, not in Android, then you can use this new intent.
