### ISSUE TITLE
Microsoft Edge not working in WSA

### ISSUE THREAD

**Issue by matinmn87** [microsoft/WSA#249]
### Steps to reproduce

Just install Microsoft Edge on WSA. When you enter the application, almost nothing is working properly. I'm creating the issue here because this apk file that I installed on WSA was tested on my phone before & was functioning properly.

### ✔️ Expected Behavior

The normal behavior of a chromium-based web browser, like on a real cell phone.

### ❌ Actual Behavior

Errors are everywhere. Nothing's working right.

![image](https://user-images.githubusercontent.com/70327745/223463141-b1eba2aa-2fd3-4639-86d8-96c3768e292d.png)

![image](https://user-images.githubusercontent.com/70327745/223464452-e7b85e21-fc5e-4d81-8b26-aa4aa3f093cc.png)

The user can't turn on sync.
![image](https://user-images.githubusercontent.com/70327745/223464520-8b625896-6cdf-49b2-ab3f-f5ffdb257937.png)

### Other Software

Microsoft Edge Mobile 110.0.158761

### Please specify the version of Windows Subsystem for Android

2301.40000.70

**Comment by kevinkieselbach** [comment]
You're probably running the ARM architecture version of Edge on an x86-64 architecture PC.  Chromium's dynamic code generation isn't compatible with Intel Bridge Technology that WSA uses for ARM emulation.  I don't think the x86-64 version of Edge for Android is publicly available, but I have confirmed that it works on WSA.  Running a full browser in WSA isn't a supported scenario since WSA redirects browser intents to the Windows default browser (although it should work if you install an x86-64 browser via ADB).  A desktop browser running natively will provide significantly better performance and a better user experience than a mobile browser running in a virtual machine.

**Comment by matinmn87** [comment]
Just for others, I tried Firefox & it is working well on WSA.

**Comment by jat001** [comment]
Same issue. I tried chrome with x86_64 architecture from [apkmirror](https://www.apkmirror.com/apk/google-inc/chrome/chrome-117-0-5938-154-release/). It still not working.
Only edge and chrome have this issue. Other browsers on play store like firefox, opera, vivaldi and brave don't have this issue.
It might be a chromium related issue?

**Comment by Cavemanchess** [comment]
When I try to Open Edge from the Play Store, it immediately crashes and closes. Other browsers from the Play Store seem to work.
