### ISSUE TITLE
open media view intents through media player or browser

### ISSUE THREAD

**Issue by 7sean68** [microsoft/WSA#268]
### Describe the solution you'd like

some apps try to open online video files through a media player on android ... I need to be able to open it on a media player on windows instead (or at least open in browser). Currently the gallery (video player) app tries to open the link but fails saying (can't play this video).

### Please specify the version of Windows Subsystem for Android

2301.40000.7.0

**Comment by jaholme** [comment]
Can you provide some more details about what type of video? Is it a specific encoding that does not work?

**Comment by 7sean68** [comment]
Format: MPEG-4
Video: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Audio: AAC

I tried another video it worked inside the gallery app in wsa ... it would be better to open in my media player on windows or even on browser on windows

**Comment by kevinkieselbach** [comment]
Can you share more details about the intents so we can update our intent filters to handle them?  Are these http/https schemes?  If you have the full URI or intent details please share those.  We redirect http/https URIs to the Windows default browser, but if the sender specifies a MIME type other than ".html", it will bypass our intent filter.  We could probably expand our http/https intent filter to handle `*/*` MIME types if that would cover this scenario.  For local files, we have to be more careful about opening on Windows because we would have to copy the file, in which case modifications wouldn't be visible to the sender.

**Comment by nieubank** [comment]
We need additional information to be able to address this request.
