### ISSUE TITLE
Android VPN connection support

### ISSUE THREAD

**Issue by matinmn87** [microsoft/WSA#275]
### Describe the solution you'd like

Because some VPNs are only available for android & not windows, I suggest adding support for VPNs both within the WSA android apps, and systemwide connections (if possible).

### Please specify the version of Windows Subsystem for Android

2301.40000.70

**Comment by matinmn87** [comment]
Any responses?

**Comment by kevinkieselbach** [comment]
The challenge with supporting Android VPN apps is that those VPNs will only apply to Android network traffic, not Windows network traffic, which may provide the user with a false sense of privacy/security since less technical users will not realize this or know which apps are covered by the VPN.  If Android VPNs could cover Windows network traffic too, we would support this, but we don't have a technical solution that meets that requirement at this time.  We are evaluating ways to improve our virtual networking but don't have any concrete plans to share.

**Comment by HotCakeX** [comment]
@kevinkieselbach 
I already use VPN and have been using VPN apps on WSA for months. The only feature you didn't implement is the ability for VPN apps to prompt for VPN connection requests, which can be easily done manually:

https://github.com/riverar/wsa-app-compatibility#vpn

I think not all of us should be prevented from using a feature just because a few people might make a false assumption about the role of VPN apps on Android. You can even show a prompt to the user letting them know that their VPN only works for Android apps.

This isolation is actually what I really appreciate about WSA.

Hopefully you'll consider this opinion too in your feature implementations.

**Comment by nieubank** [comment]
Tracking under #272
