### ISSUE TITLE
Sending emails with attachments

### ISSUE THREAD

**Issue by cody-howell7** [microsoft/WSA#282]
### Is your feature request related to a problem? Please describe

When attempting to send an email through WSA, a file explorer will open to the downloads folder with the attachments that were requested to be included in the new mail item and the selected mail provider will open with a new email but it does not include any of the attachments that are in the downloads folder.

### Describe the solution you'd like

When sending an email with attachments, it should include the attachments in the new email that is created from the selected mail provider.

### Describe alternatives you've considered

Using react-native, I have tried a few different mail libraries which both work on android to include the attachments in the new email.

https://docs.expo.dev/versions/latest/sdk/mail-composer/
https://github.com/react-native-share/react-native-share

### Please specify the version of Windows Subsystem for Android

2302.40000.9.0

**Comment by kevinkieselbach** [comment]
Unfortunately, there is no standard way to send an email with attachments on Windows.  The "mailto" protocol is widely supported by most email apps (even Progressive Web Apps), so that's what we use, but it doesn't support attachments.  The MAPI API supports attachments but only works with Win32 Outlook, so we can't use that for a generally applicable solution.  Showing the attachments in the downloads folder is the mitigation we came up with that at least makes it relatively easy to attach them.  For example, many email apps support drag-and-drop from File Explorer.
