### ISSUE TITLE
MTP devices open in WSA after installation of WSA

### ISSUE THREAD

**Issue by kvxrun** [microsoft/WSA#325]
### Steps to reproduce

1. Install WSA
2. Connect any MTP device (eg. Android device) in File Transfer mode
3. Try opening the Internal storage/any folder in MTP device
4. Either nothing happens or WSA is launched

### ✔️ Expected Behavior

MTP device folders/internal storage must open in Windows Explorer itself

### ❌ Actual Behavior

WSA launches or nothing happens

### Other Software

1. MiX File Explorer within WSA

### Please specify the version of Windows Subsystem for Android

2305.40000.2.0

**Comment by jaholme** [comment]
This could be due to MiX file explorer. Please try without that and report if the problem still occurs via Feedback Hub(Windows Key + F)

**Comment by HeyItsJono** [comment]
Can confirm this was the issue for me, which is unfortunate because MIX is an otherwise good file explorer. Thanks for the heads up. Wish there was a workaround that didn't require uninstalling it.

**Comment by kristibektashi** [comment]
The actual reason for this issue is because Mix File Explorer takes over the `folder:` protocol which is supposed to be associated with Windows Explorer (since it apparently uses it to access MTP folders), however you are unable to set it back after installing Mix because for some reason Windows Explorer doesn't show up in the list of available apps for the protocol unless you uninstall Mix (personally I also had to uninstall MediaInfo in order for Windows Explorer to show up).

This in my opinion isn't a WSA bug (which properly does it's job of redirecting associated protocols from Android apps to Windows) or a Mix bug (which the developers probably never predicted people would run it on Windows), but rather an oversight in Windows itself. I believe that Windows should detect when an app (whether it's from WSA or not) tries to take over important system protocols like `folder:`, and either prevent the app from taking over the protocol or at least allow you to change it back.

**Comment by thelittleerik** [comment]
Its April and the issue still isn't fixed. Do i have to uninstall WSA just so my Thunderbird client won't keep opening links on WSA?
