### ISSUE TITLE
File transfer to app data storage folder

### ISSUE THREAD

**Issue by jake-brown-maps** [microsoft/WSA#326]
### Is your feature request related to a problem? Please describe

The problem that we are hoping to solve with the WSA file transfer (Win 11 -> WSA) is to provide the capability for our (Field Maps) users to copy files from their windows device into the app data storage folder.  This capability gives our users the ability to side-load their large datasets into the location where our app can load them.  

### Describe the solution you'd like

The Android file app available in `WSA settings` supports the ability to move files from the logged in users document folder to the WSA app data folder.

Our app specific supported file extensions: .vtpk, .tpkx, .vptkx, mmpk, .tpk

### Describe alternatives you've considered

Load ADB libraries and run command: 

adb.exe push c:\Users\<login>\Documents\RedlandsTiles.tpk /sdcard/Android/data/com.esri.fieldmaps/files/basemaps

### Please specify the version of Windows Subsystem for Android

2305.40000.2.0

**Comment by kevinkieselbach** [comment]
Android's security model prevents apps, including Android Files, from modifying other apps' private app data folders.  Even on Windows where it's technically possible for users to modify app data in File Explorer, app data is hidden by default because it isn't something end users should need to access.

Instead, I would recommend using Android's Storage Access Framework (https://developer.android.com/guide/topics/providers/document-provider).  ACTION_OPEN_DOCUMENT will open a file picker window hosted by Android Files from which the user can select a file under "Subsystem for Android(TM) > Windows".  Your app will gain access to the selected file and can either copy the file into your private app data folder or call https://developer.android.com/reference/android/content/ContentResolver#takePersistableUriPermission(android.net.Uri,%20int) to persist the access across reboots and continue to access it directly from Windows.  Storage Access Framework is Android's recommended best practice for accessing user documents, and file pickers are a familiar experience to Windows users.

**Comment by kevinkieselbach** [comment]
You can also use ACTION_OPEN_DOCUMENT_TREE to have the user select a folder instead of a file if they need to share many asset files.
