### ISSUE TITLE
[Bug] WSA automatically starts when open certain web links on Windows

### ISSUE THREAD

**Issue by h4rvey-g** [microsoft/WSA#342]
### Steps to reproduce

Open a web link in windows applications and WSA will automatically start. This issue only occur on some apps, like [Fluent Search](https://github.com/adirh3/Fluent-Search) and [SnipDo](https://snipdo-app.com/). Some other apps can still open links properly.

### ✔️ Expected Behavior

Open a webpage on Windows default browser like usual.

### ❌ Actual Behavior

Immediately after click the link, WSA is started. And the webpage will only be opened on Windows browser after WSA starts running. I'd like to stop this.

### Please specify the version of Windows Subsystem for Android

2305.40000.5.0

**Comment by dabhattimsft** [comment]
Hi, can you provide more details? Are there specific links invoked by Fluent Search and SnipDo which open WSA? Are there android apps installed which can potentially handle those links?

**Comment by Papes96** [comment]
Hello! I also see this problem when I open amazon links from Notion desktop app. Hope you can fix it. Thanks for your hard work

**Comment by babaolanqiu** [comment]
1. Seems Google and Amazon sites will start WSA. Other links are ok for now.
2. I have GApps and Amazon appstore installed. But I have disabled the "Open supported link" toggle in them.

**Comment by kvxrun** [comment]
I have GApps installed too, and I have an issue with WSA starting when I try to open MTP devices. Can you confirm that too?

**Comment by dabhattimsft** [comment]
Can you elaborate more on "open MTP device"? How are you accessing them specifically? Are they opened via http link?

**Comment by kvxrun** [comment]
Connect an Android device in File Transfer mode. Try accessing the files on Internal storage through Windows. WSA launches and files can't be accessed. Check [this](https://github.com/microsoft/WSA/issues/325)

**Comment by Rings4** [comment]
I'm getting this behaviour too. I clicked a youtu.be url and had to wait 10+ seconds for WSA to start before it opened in my browser anyway. When WSA is running, it opens immediately in my browser. 

It appears that youtu.be (not sure about regular youtube) urls require WSA to be running in order for windows to open them in the default browser, which is strange.

**Comment by OliverLx** [comment]
I had the problem probably since I installed Firefox in WSA. I used the context menu of Android Firefox in the Windows 11 start menu, app settings and changed the property _browser app_ of firefox from _Firefox_ to _Windows default_.
Since then my Amazon links in Microsoft Teams are opened with Windows Edge instead of Firefox in WSA.

**Comment by shinji257** [comment]
I want to confirm this as well.  I disabled "Open By Default" on Google (I'm running a package that has Google Play added) and it still opens google links by loading WSA first then finally relaying to the default browser in Windows.  I would expect that WSA wouldn't try to process the URL if related applications that claim to be able to open them have that functionality turned off.  Other links skip WSA as expected.

**Comment by Hayao0819** [comment]
I am experiencing the same problem: when I click on the Amazon link in the desktop version of LINE Messages, WSA starts up and then forwards me to my default browser.

**Comment by SayuShira** [comment]
It is still happening e.g. in Thunderbird when checking the status of a package. Casually and indefinitely eating 2GB of RAM to open a web link!
Open by default for Amazon is disabled. http/https defaults are on Firefox (Windows).

Why even is it that you pass information about what I click to WSA and Amazon? It does not and should not know that I want to open a browser link. It is NOT involved per my settings!

**Comment by pc-v2** [comment]
could be "Windows default app" app is the culprit, just guessing

**Comment by dabhattimsft** [comment]
Hi, we have fixed checked in and next release should have it.

**Comment by kvxrun** [comment]
Is the fix included in the latest 2311 update?

**Comment by Gh0styyy** [comment]
A year on from when this was first posted - Issue still exists.

**Comment by OliverLx** [comment]
It does not occur any longer in my systems (at least I do not remember the last time), but I do not have any browser (such as Firefox) installed in WSA any longer.

**Comment by TheShark27** [comment]
I found a definitive fix after a day troubleshooting this.

1. **Make sure WSA is turned off** before proceeding.
2. **Navigate to the following registry location** in Windows Registry Editor:
   ```
   Computer\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\MicrosoftCorporationII.WindowsSubsystemForAndroid_8wekyb3d8bbwe\AppUriHandlers\
   ```
3. **Delete the problematic site keys** under the `AppUriHandlers` folder. For example, delete the `google.com` key if it's causing issues.

### How to Test:
1. In **Google Chrome**, type `microsoft-edge:google.com` in the address bar **while WSA is turned off**.
2. Before the fix, this should open Google through WSA.
3. After the fix, a dialog should pop up asking whether to open with **WSA** or **Chrome**. Select **Chrome**.
4. The first time you do this, it might open a strange XML file, but on the second attempt, the link will work correctly in Chrome.

Just to be sure it won't happen again, I deleted the entire AppUriHandlers folder, so that other links, such as amazon.com, won't open in WSA anymore.

**Comment by h4rvey-g** [comment]
Thank you @TheShark27 ! This works like a charm! So glad there is a solution after microsoft discontinued WSA.

**Comment by OZ20** [comment]
@TheShark27 Thank you, I'm glad search engine still can find this. LLMs can't figure it out yet!
