### ISSUE TITLE
Compatibility option missing

### ISSUE THREAD

**Issue by SonaliBendre** [microsoft/WSA#349]
### Steps to reproduce

Install latest ver. of wsa

### ✔️ Expected Behavior

Compatibility section should be there

### ❌ Actual Behavior

![image](https://github.com/microsoft/WSA/assets/73757361/034393e9-c646-40f6-9023-7833a4ea73ae)

### Please specify the version of Windows Subsystem for Android

![image](https://github.com/microsoft/WSA/assets/73757361/4cb5ce39-37cb-4cbe-a44a-1983aef0de9c)

**Comment by kevinkieselbach** [comment]
We removed the compatibility toggles because there was a lot of confusion around what effect they had and when they were appropriate to enable.  We may bring them back in the future if we can get the user experience right.  To help us prioritize investments, which compatibility toggles were you using and why?

**Comment by HALLODEERE** [comment]
The compatibility toggles were the only way I could get my smart lights app (Globe Suite, sideloaded via apk) to properly render on my computer. The latest update has again led to an unusable experience

**Comment by aicynide** [comment]
It was useful for "Battleground Mobile: India" game

**Comment by teslavitas** [comment]
I need a way to rotate maps, something like Tap Spot in Bluestacks

**Comment by Astra060** [comment]
This is the laziest thing you could have done. Putting it under Experimental features would the least you could do. Typical Microsoft!
