### ISSUE TITLE
Local network access doesn't work properly.

### ISSUE THREAD

**Issue by NT-Macgyver** [microsoft/WSA#371]
### Steps to reproduce

Download an apk of a Wi-Fi analyzer app from F-Droid or backup a wifi analyzer app in your Android phone then transfer it to your PC.

Turn on Developer mode in WSA, connect with "adb connect 'ip address:port'", then install the wifi analyzer apk with "adb install 'path'"

Turn on local network access in the experimental features.

open the wifi analyzer app you will see VirtWifi and you won't see any other Wi-Fi networks in your area.

### ✔️ Expected Behavior

This should be happening. 

![with_version_2305 40000 6 0](https://github.com/microsoft/WSA/assets/60831467/e2c21bcf-98f6-456b-8d6e-c667df205c95)

you can see the Wi-Fi network you are connected to and the other Wi-Fi access points in your area. I got this result with WSA version 2305.40000.6.0 with Advanced Networking Turned on.

### ❌ Actual Behavior

This is what happens with the latest version.

![with_version_2306 40000 4 0](https://github.com/microsoft/WSA/assets/60831467/b3d26790-cecc-45ba-9998-003e92132415)

You see 'VirtWifi" and the other wifi networks aren't showing.

### Other Software

WIFIAnalyzer from F-Droid.

### Please specify the version of Windows Subsystem for Android

2306.40000.4.0

**Comment by nieubank** [comment]
Unfortunately this was a feature in the previous implementation of "Advanced networking" that has not been included in the latest iteration of this preview feature as it gets closer to being production ready. 

Android itself, due to privacy concerns, continues to add more restrictions to apps accessing to wifi scanning and adapter management so the added complexity of mirroring network interfaces themselves into WSA is not a scenario we intent to support as the local network access feature rolls out.

**Comment by richgo** [comment]
Any chance we can get this on the backlog for a future iteration please @nieubank ? 
I'm trying to run the Android Naim app for my Hi-Fi system and it simply wont work the current network implementation. Bluetooth support would be helpful too...
