### ISSUE TITLE
Youtube opens Windows Caption settings when it is expected to open its own settings

### ISSUE THREAD

**Issue by mio-19** [microsoft/WSA#411]
### Steps to reproduce

+ Install some version of Youtube. Either original or modified apk or from Play Store with modified wsa by lsposed https://github.com/LSPosed/MagiskOnWSALocal
+ Your Avatar -> Settings -> Captions
+ See Windows Accessibility Settings

### ✔️ Expected Behavior

open youtube's own settings

### ❌ Actual Behavior

 See Windows Accessibility Settings

### Please specify the version of Windows Subsystem for Android

2307.40000.5.0

**Comment by jaholme** [comment]
Hello, thank you for the feedback but this issue is by design. On an Android 13 device, YouTube open's the Android system settings for caption controls not a YouTube specific settings page. 
In WSA we have integrated caption controls with the Windows OS, which is why this redirects to the Windows settings page.
