### ISSUE TITLE
Prevent Windows Subsystem for Android from booting up by its own self

### ISSUE THREAD

**Issue by FabPhntm** [microsoft/WSA#448]
### Is your feature request related to a problem? Please describe

Roughly every hour or so, Windows Subsystem for Android erroneously boots by its own self for 7 minutes or so, then shuts itself down. No app shows on-screen or anything, and everything happens without input.

### Describe the solution you'd like

Add a feature in Advanced Settings where nothing can run at all and Windows Subsystem for Android can't boot itself up, except when i boot up the Windows Subsystem for Android myself manually.

### Describe alternatives you've considered

I set Subsystem Resources as "As needed", and disabled notifications in Windows Settings. I also tried Developer Options in the Windows Subsystem for Android itself but it appears the settings there only apply AFTER the subsystem is active.

### Please specify the version of Windows Subsystem for Android

2308.40000.3.0

**Comment by FabPhntm** [comment]
Side note but also sometimes, when Windows Subsystem for Android isn't even active by my doing, a window saying "Windows Subsystem for Android is attempting to restart" almost as if it crashed. Why does it do that? What's the point? Why does it boot up itself when i turned off notifications in the windows settings indicating that i have no use for it to be in the background?

**Comment by dabhattimsft** [comment]
Hi, Thanks for the feedback. Disabling notifications via Settings App>System>Notifications only disables [Toast notifications](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/toast-notifications-overview). It does not disable push notifications. WSA might be getting started due to that. To disable push notifications you can go to, Settings App> Apps> Installed Apps> Windows Subsystem for Android™ and Android Apps > Advanced options and chose "Never" for "Let this app run in background" drop down.

![Recording 2023-10-09 163334](https://github.com/microsoft/WSA/assets/47045043/5be423ec-c5c0-43fe-ac7e-5035dd03e4ca)
