### ISSUE TITLE
App flashes when moving app window from external monitor to internal monitor

### ISSUE THREAD

**Issue by rp1231** [microsoft/WSA#97]
### Steps to reproduce

I use an external monitor connected to my laptop.
When I move the window of the apps from the internal to external monitor and vice versa,
There is some sort of flashing/ flickering that occurs.

And in some situations, because of this, some things get reset and start from the beginning.
i.e. it loses its progress and starts from the beginning.

one example I can give is that the youtube shorts in the youtube app start playing from the beginning  when I move the window from one screen to another.

I don't know if this is due to nvidia optimus on laptops but thought I'd mention it just in case.

### ✔️ Expected Behavior

The app should not flash/flicker when moving the  window from one monitor to another

### ❌ Actual Behavior

The app flashes/flickers when moving the window from one monitor to another.

### Please specify the version of Windows Subsystem for Android

2208.40000.5.0

**Comment by nieubank** [comment]
This is generally expected behavior. See https://developer.android.com/guide/topics/resources/runtime-changes for how to handle configuration changes such as DPI, screen size, etc. that may be associated with moving an app from one display to another. 

The experience should be similar to an Android device connected to external monitor in freeform windowing mode. Let us know if that's not the case with some additional specifics on how to reproduce the problem.

**Comment by nieubank** [comment]
> @nieubank It's not just flashing that occurs, If you're playing a video for example, the video will start from the beginning if moved to the external screen and vice versa.
> 
> To reproduce, you can attach an external monitor to a laptop and play an mp4 video from the files app in wsa. While the video is playing, if you move the window to another screen, the video starts from the beginning all over again.
> 
> I'm not able to reopen this issue for some reason.

Unfortunately this is still expected behavior on apps that are not designed to handle configuration changes. To ensure resources are populated correctly and updated, Android will just restart the activity and this is entirely up to the app as to how they handle it. Older apps that aren't updated since Android 6 or so typically are the ones that have these problems. If you're the developer reference this documentation. Otherwise, you'll need to reach out to the developer. 

https://developer.android.com/guide/topics/resources/runtime-changes
